### ISSUE TITLE
fix build fail

### ISSUE THREAD

**Issue by jesusdoza** [Pkasu06/Booking-App#22]
build says location reference fail

```
> Export encountered errors on following paths:
        /admin/appointments/page: /admin/appointments
        /admin/dashboard/page: /admin/dashboard
        /admin/inventory/page: /admin/inventory
        /admin/page: /admin
``` 

```

ReferenceError: location is not defined
    at Z:\gitSpace\team\Booking-App\client\.next\server\chunks\831.js:1:6829
    at Z:\gitSpace\team\Booking-App\client\.next\server\chunks\831.js:1:7603
    at t.startTransition (Z:\gitSpace\team\Booking-App\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:108524)
    at Object.push (Z:\gitSpace\team\Booking-App\client\.next\server\chunks\831.js:1:7591)
    at c (Z:\gitSpace\team\Booking-App\client\.next\server\app\admin\page.js:1:3835)
```

**Comment by jesusdoza** [comment]
useRouter depends on component being mounted so adding a useEffect to wrap the router.push for redirecting if user is not logged in is needed or else it will fail to build
